apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: flux-system
  namespace: flux-system
spec:
  interval: 5m
  path: ./clusters/production  # Flux will automatically find all YAMLs here
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
