# clusters/production/flux-system-kustomization.yaml
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: flux-system
  namespace: flux-system
spec:
  interval: 5m
  path: ./clusters/production
  sourceRef:
    kind: GitRepository
    name: flux-system
  prune: true
  # Explicitly declare resources to process
  resources:
  - nginx-release.yaml
  - flux-system-kustomization.yaml
