# clusters/production/nginx-release.yaml
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: nginx
  namespace: flux-system
spec:
  interval: 5m
  chart:
    spec:
      chart: ./clusters/production/nginx
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    # Add serviceAccount configuration here
    serviceAccount:
      create: true
      name: nginx
      automount: true  # Add this if missing in your template
    
    # Existing values
    image:
      repository: nginxinc/nginx-unprivileged
      tag: "1.25.4"
    service:
      type: ClusterIP
      port: 8080
    securityContext:
      capabilities:
        add: ["NET_BIND_SERVICE"]
      readOnlyRootFilesystem: false
    volumes:
      - name: nginx-cache
        emptyDir: {}
    volumeMounts:
      - name: nginx-cache
        mountPath: /var/cache/nginx
    
    # Add other values from clusters/production/nginx/values.yaml as needed
    replicaCount: 1
    resources:
      limits:
        cpu: 500m
        memory: 512Mi
      requests:
        cpu: 100m
        memory: 128Mi
