apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: nginx
  namespace: flux-system
spec:
  interval: 5m
  chart:
    spec:
      chart: ./clusters/production/nginx
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
  values:
    serviceAccount:
      create: true
      automountServiceAccountToken: true  # Changed from 'automount: false'
      name: "nginx-serviceaccount"  # Added explicit name

    # Add podDisruptionBudget for better availability
    podDisruptionBudget:
      enabled: true
      minAvailable: 1
