apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nginx
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      chart: ./nginx
      sourceRef:
        kind: GitRepository
        name: flux-system
  values:
    image:
      repository: nginx
      tag: "1.25.4"
