replicaCount: 2

image:
  repository: nginx
  tag: "1.25.4"
  pullPolicy: IfNotPresent

serviceAccount:
  create: true
  name: nginx

service:
  type: ClusterIP
  port: 80
  targetPort: 80

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 128Mi

livenessProbe: {}
readinessProbe: {}
startupProbe: {}

