replicaCount: 2

image:
  repository: nginxinc/nginx-unprivileged  # Changed to non-root image
  tag: "1.25.4"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8080
  targetPort: 8080

podSecurityContext:
  runAsNonRoot: true
  runAsUser: 101
  fsGroup: 101
  runAsGroup: 101

securityContext:
  capabilities:
    add: ["NET_BIND_SERVICE"]  # Added for port binding
  readOnlyRootFilesystem: false
  allowPrivilegeEscalation: false

volumes:
  - name: nginx-cache
    emptyDir: {}
  - name: nginx-tmp
    emptyDir: {}
  - name: nginx-run
    emptyDir: {}

volumeMounts:
  - name: nginx-cache
    mountPath: /var/cache/nginx
  - name: nginx-tmp
    mountPath: /tmp
  - name: nginx-run
    mountPath: /var/run

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    memory: 512Mi

autoscaling:
  enabled: false

ingress:
  enabled: false

livenessProbe:
  httpGet:
    path: /
    port: 8080
  initialDelaySeconds: 5
  periodSeconds: 10
  failureThreshold: 3

readinessProbe:
  httpGet:
    path: /
    port: 8080
  initialDelaySeconds: 2
  periodSeconds: 5

config: |
  user nginx;
  worker_processes auto;
  error_log /dev/stderr warn;
  pid /var/run/nginx.pid;

  events {
    worker_connections 1024;
  }

  http {
    server {
      listen 8080;
      server_name _;
      
      access_log /dev/stdout;
      
      location / {
        root /usr/share/nginx/html;
      }
      
      location /status {
        stub_status;
      }
    }
  }

extraEnvVars:
  - name: NGINX_ENV
    value: production

# Add pod annotations
podAnnotations:
  prometheus.io/scrape: "true"
  prometheus.io/port: "8080"
