replicaCount: 2

image:
  repository: nginxinc/nginx-unprivileged
  tag: "1.25.4"
  pullPolicy: IfNotPresent

serviceAccount:
  create: true
  name: nginx
  automount: true
  annotations: {}

service:
  type: ClusterIP
  port: 80
  targetPort: 80

podSecurityContext:
  runAsNonRoot: true
  runAsUser: 101
  fsGroup: 101

securityContext:
  capabilities:
    drop: [ALL]
  readOnlyRootFilesystem: true
  allowPrivilegeEscalation: false

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    memory: 256Mi

autoscaling:
  enabled: false
  # minReplicas: 2
  # maxReplicas: 10
  # targetCPUUtilizationPercentage: 80

ingress:
  enabled: false
  # className: nginx
  # hosts:
  #   - host: nginx.example.com
  #     paths:
  #       - path: /
  #         pathType: Prefix

livenessProbe:
  httpGet:
    path: /
    port: 80
  initialDelaySeconds: 5
  periodSeconds: 10
  failureThreshold: 3

readinessProbe:
  httpGet:
    path: /
    port: 80
  initialDelaySeconds: 2
  periodSeconds: 5

startupProbe:
  httpGet:
    path: /
    port: 80
  initialDelaySeconds: 1
  periodSeconds: 5
  failureThreshold: 30

## Custom NGINX configuration
config: |
  events {
    worker_connections 1024;
  }

  http {
    server {
      listen 80 default_server;
      location / {
        return 200 'NGINX is working!';
      }
      location /status {
        stub_status;
      }
    }
  }

## Environment variables
extraEnvVars:
  - name: NGINX_ENV
    value: production

